apiVersion: apps/v1
kind: Deployment
metadata:
  name: documenso-app
  namespace: thesis
  labels:
    name: dev-thesis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documenso-app
  template:
    metadata:
      labels:
        app: documenso-app
    spec:
      # wait for postgres-service to run first
      initContainers:
      - name: init-wait-for-db
        image: alpine
        command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 postgres-service 5432 && exit 0 || sleep 3; done; exit 1"]
      - name: db-migration
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
      containers:
        - name: documenso-container
          image: documenso-container:v1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
              name: app-sec
          livenessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3