apiVersion: apps/v1
kind: Deployment
metadata:
  name: documenso-deployment
  namespace: thesis
  labels:
    name: dev-thesis-app
spec:
  selector:
    matchLabels:
      app: documenso-deployment
  template:
    metadata:
      labels:
        app: documenso-deployment
    spec:
      initContainers:
      # wait for db-service to run first
      - name: init-wait-for-db
        image: alpine
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: app-env-sec
        command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 $DB_HOST 5432 && exit 0 || sleep 3; done; exit 1"]
      # run migration
      - name: db-migration
        image: ragil88/documenso-migration:v1.0
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: app-env-sec
      containers:
        - name: documenso-container
          image: ragil88/documenso-app:v1.0
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-env-sec
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "700m"
              memory: "1024Mi"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
