apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app
  namespace: thesis
  labels:
    name: dev-thesis-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: documenso-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
