apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels: 
    name: dev-thesis-app
  namespace: thesis
spec:
  type: NodePort
  selector:
    app: documenso-deployment
  ports:
    - port: 80
      targetPort: 3000
