apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: db-stateful
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
              name: postgres-cfg
          volumeMounts:
            - name: postgres-data-claim
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data-claim
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi