apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: thesis
  labels: 
    name: dev-thesis-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
              name: postgres-sec
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-storage-claim