apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: dev-thesis-db
  namespace: thesis
spec:
  type: ClusterIP
  selector:
    app: postgres-statefulset
  ports:
  - port: 5432
    name: postgres-port