apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cfg
  labels:
    app: my-deployment-cfg
data:
  POSTGRES_DB: documenso_db
  POSTGRES_USER: documenso_user
  POSTGRES_PASSWORD: documenso_password

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cfg
  labels:
    app: my-deployment-cfg
data:
  DATABASE_URL: postgres://documenso_user:documenso_password@database:5432/documenso_db
  NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000
  NEXTAUTH_SECRET: my-super-secure-secret
  NEXTAUTH_URL: http://localhost:3000
  SENDGRID_API_KEY:
  SMTP_MAIL_HOST: inbucket
  SMTP_MAIL_PORT: 2500
  SMTP_MAIL_USER: username
  SMTP_MAIL_PASSWORD: password
  MAIL_FROM: admin@example.com
  NEXT_PUBLIC_ALLOW_SIGNUP: true