apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage
  namespace: thesis
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: thesis
    name: db-storage-claim
  gcePersistentDisk:
    pdName: gke-pv-disk
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage-claim
  namespace: thesis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi