apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/location
  claimRef:
    namespace: thesis
    name: db-storage-claim
  gcePersistentDisk:
    pdName: gke-pv-disk
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50