apiVersion: v1
kind: Secret
metadata:
  name: database-env-sec
  labels:
    app: dev-thesis-sec
type: opaque
stringData:
  POSTGRES_DB: documenso_db
  POSTGRES_USER: documenso_user
  POSTGRES_PASSWORD: documenso_password

---

apiVersion: v1
kind: Secret
metadata:
  name: app-env-sec
  labels:
    app: dev-thesis-sec
type: opaque
stringData:
  DATABASE_URL: postgres://documenso_user:documenso_password@db-service.thesis.svc.cluster.local:5432/documenso_db
  NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000
  NEXTAUTH_SECRET: my-super-secure-secret
  NEXTAUTH_URL: http://localhost:3000
  SENDGRID_API_KEY: 
  MAIL_FROM: admin@example.com
  NEXT_PUBLIC_ALLOW_SIGNUP: true